<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        Student::insert([
            [
                'surname' => 'Данченко',
                'name' => 'Егор',
                'patronymic' => 'Игоревич',
                'birthday' => '2004-09-16',
                'group_id' => 1,
            ],
            [
                'surname' => 'Музычкин',
                'name' => 'Тимофей',
                'patronymic' => 'Алексеевич',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Иконн',
                'name' => 'Диана',
                'patronymic' => 'Андреевна',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Калиничева',
                'name' => 'Алина',
                'patronymic' => 'Сергеевна',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Алексюк',
                'name' => 'Ульяна',
                'patronymic' => 'Александрона',
                'birthday' => '2004-09-17',
                'group_id' => 1,
            ],
            [
                'surname' => 'Батюк',
                'name' => 'Егор',
                'patronymic' => 'Александрович',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Бельский',
                'name' => 'Василий',
                'patronymic' => 'Васильевич',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Гаврилов',
                'name' => 'Степан',
                'patronymic' => 'Дмитриевич',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Грищенко',
                'name' => 'Роман',
                'patronymic' => 'Дмитриевич',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Даниленко',
                'name' => 'Михаил',
                'patronymic' => 'Юрьевич',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Жовнер',
                'name' => 'Евгений',
                'patronymic' => 'Сергеевич',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Жулего',
                'name' => 'Артем',
                'patronymic' => 'Александрович',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Закружный',
                'name' => 'Егор',
                'patronymic' => 'Сергеевич',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Каршанков',
                'name' => 'Павел',
                'patronymic' => 'Денисович',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Лебенков',
                'name' => 'Денис',
                'patronymic' => 'Николаевич',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Макеев',
                'name' => 'Дмитрий',
                'patronymic' => 'Витальевич',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Нестерович',
                'name' => 'Илья',
                'patronymic' => 'Владимирович',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Прищепов',
                'name' => 'Максим',
                'patronymic' => 'Геннадьевич',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Смирнов',
                'name' => 'Павел',
                'patronymic' => 'Витальевич',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Титов',
                'name' => 'Егор',
                'patronymic' => 'Витальевич',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Трибой',
                'name' => 'Елена',
                'patronymic' => 'Ильинична',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Тукач',
                'name' => 'Даниил',
                'patronymic' => 'Михайлович',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Черкасов',
                'name' => 'Александр',
                'patronymic' => 'Александрович',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Чернякова',
                'name' => 'Алина',
                'patronymic' => 'Сергеевна',
                'birthday' => $this->getBirthday(),
                'group_id' => 1,
            ],
            [
                'surname' => 'Анохов',
                'name' => 'Евгений',
                'patronymic' => 'Александрович',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Бортник',
                'name' => 'Кира',
                'patronymic' => 'Валерьевна',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Горбик',
                'name' => 'Артем',
                'patronymic' => 'Евгеньевич',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Данченко',
                'name' => 'Екатерина',
                'patronymic' => 'Алексеевна',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Денисенко',
                'name' => 'Рустам',
                'patronymic' => 'Леонидович',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Жбанков',
                'name' => 'Арсений',
                'patronymic' => 'Андреевич',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Журавлева',
                'name' => 'Анастасия',
                'patronymic' => 'Александровна',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Карлашова',
                'name' => 'Анастасия',
                'patronymic' => 'Дмитриевна',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Клементьев',
                'name' => 'Иван',
                'patronymic' => 'Егорович',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Ковтуненко',
                'name' => 'Елена',
                'patronymic' => 'Дмитриевна',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Кондаков',
                'name' => 'Артем',
                'patronymic' => 'Александрович',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Коркуц',
                'name' => 'Владислав',
                'patronymic' => 'Дмитриевич',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Кустов',
                'name' => 'Константин',
                'patronymic' => 'Дмитриевич',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Лопич',
                'name' => 'Алеся',
                'patronymic' => 'Сергеевна',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Майданский',
                'name' => 'Глеб',
                'patronymic' => 'Андреевич',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Науменко',
                'name' => 'Иван',
                'patronymic' => 'Дмитриевич',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Папкович',
                'name' => 'Ксения',
                'patronymic' => 'Константиновна',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Пинчук',
                'name' => 'Татьяна',
                'patronymic' => 'Александровна',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Подерачев',
                'name' => 'Владислав',
                'patronymic' => 'Владимирович',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Рафальская',
                'name' => 'Евгения',
                'patronymic' => 'Петровна',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Сафаралиев',
                'name' => 'Али-Ага',
                'patronymic' => 'Мамедович',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Селиверстова',
                'name' => 'Дарья',
                'patronymic' => 'Владимировна',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Степаненко',
                'name' => 'Анастасия',
                'patronymic' => 'Иванова',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Трофимович',
                'name' => 'Дарья',
                'patronymic' => 'Игоревна',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
            [
                'surname' => 'Яковенко',
                'name' => 'Миланна',
                'patronymic' => 'Евгеньевна',
                'birthday' => $this->getBirthday(17),
                'group_id' => 2,
            ],
        ]);
    }

    protected function getBirthday($startDate = 20)
    {
        $endDate = $startDate - 1;
        return Carbon::parse(fake()->dateTimeBetween("-$startDate years", "-$endDate years"))->format('Y-m-d');
    }
}
