export * from './base.table'
export * from './characteristic.table'
export * from './characteristic-student.table'
export * from './course.table'
export * from './curator.table'
export * from './group.table'
export * from './specialty.table'
export * from './student.table'
